# Generated by Django 4.2.7 on 2023-12-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='em_analise',
            field=models.BooleanField(default=True),
        ),
    ]
