# Generated by Django 4.2.7 on 2023-12-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_customuser_em_analise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='em_analise',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('analise', 'Em Análise'), ('aprovado', 'Aprovado')], default='analise', max_length=10),
        ),
    ]
