# Generated by Django 4.2.7 on 2023-12-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_remove_customuser_em_analise_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_credit_card',
            field=models.BooleanField(default=False),
        ),
    ]
