# Generated by Django 4.2.7 on 2023-12-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_customuser_available_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='available_balance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='has_credit_card',
        ),
        migrations.AddField(
            model_name='customuser',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
