# Generated by Django 4.2.7 on 2023-12-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_remove_customuser_available_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
