# Generated by Django 4.2.7 on 2023-12-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_transfer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
